/**
 * Dosswerks Arcade Jukebox - Track Manifest
 * Auto-generated by scripts/generate-tracks.js
 * Generated: 2026-05-13T16:48:05.508Z
 *
 * To regenerate: node scripts/generate-tracks.js
 *
 * Playlists are loaded via ?playlist=<key> query parameter.
 * Default playlist is "default" when no parameter is specified.
 */
window.PLAYLISTS = {
  "default": {
    name: "Dosswerks Arcade Jukebox",
    tracks: [
      'Barrel Bears.mp3',
      'Cant Drive 55.mp3',
      'Dagon.mp3',
      'Fish Food - Tank 1.mp3',
      'Fish Food - Tank 2.mp3',
      'Fish Food - Tank 3.mp3',
      'Fish Food - Tank 4.mp3',
      'Fish Food - Tank 5.mp3',
      'Fish Food - Tank 6.mp3',
      'Innsmouth Invaders - Confrontation.mp3',
      'Innsmouth Invaders - Onslaught.mp3',
      'Krampus In The Village.mp3',
      'Mountains Of Madness - Campsite.mp3',
      'Mountains Of Madness - Ice Cave.mp3',
      'Phantasm - Silver Spheres.mp3',
      'Runway Rush.mp3',
      'Sky Snacker.mp3',
    ]
  }
};
