/**
 * Dosswerks Arcade Jukebox - Track Manifest
 * Auto-generated by scripts/generate-tracks.js
 * Generated: 2026-05-08T23:42:41.061Z
 *
 * To regenerate: node scripts/generate-tracks.js
 */
window.TRACKS = [
  'Barrel Bears.mp3',
  'Can\'t Drive 55.mp3',
  'Dagon.mp3',
  'Innsmouth Invaders - Confrontation.mp3',
  'Innsmouth Invaders - Onslaught.mp3',
  'Krampus In The Village.mp3',
  'Mountains Of Madness - Campsite.mp3',
  'Mountains Of Madness - Ice Cave.mp3',
  'Phantasm - Silver Spheres.mp3',
  'Runway Rush.mp3',
  'Sky Snacker.mp3',
];
