/**
 * Dosswerks Arcade Jukebox - Track Manifest
 * Auto-generated by scripts/generate-tracks.js
 * Generated: 2026-05-09T00:08:37.318Z
 *
 * To regenerate: node scripts/generate-tracks.js
 *
 * Playlists are loaded via ?playlist=<key> query parameter.
 * Default playlist is "default" when no parameter is specified.
 */
window.PLAYLISTS = {
  "default": {
    name: "Dosswerks Arcade OST",
    tracks: [
      'Barrel Bears.mp3',
      'Can\'t Drive 55.mp3',
      'Dagon.mp3',
      'Innsmouth Invaders - Confrontation.mp3',
      'Innsmouth Invaders - Onslaught.mp3',
      'Krampus In The Village.mp3',
      'Mountains Of Madness - Campsite.mp3',
      'Mountains Of Madness - Ice Cave.mp3',
      'Phantasm - Silver Spheres.mp3',
      'Runway Rush.mp3',
      'Sky Snacker.mp3',
    ]
  }
};
