#!/usr/bin/env node
/**
 * Generate tracks.js
 * Scans the assets/ directory for MP3 files and regenerates tracks.js.
 *
 * Usage: node scripts/generate-tracks.js
 */

import { readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const assetsDir = join(__dirname, '..', 'assets');
const outputFile = join(__dirname, '..', 'tracks.js');

try {
  const files = readdirSync(assetsDir)
    .filter((f) => f.toLowerCase().endsWith('.mp3'))
    .sort();

  const content = `/**
 * Dosswerks Arcade Jukebox - Track Manifest
 * Auto-generated by scripts/generate-tracks.js
 * Generated: ${new Date().toISOString()}
 *
 * To regenerate: node scripts/generate-tracks.js
 */
const TRACKS = [
${files.map((f) => `  '${f}',`).join('\n')}
];
`;

  writeFileSync(outputFile, content, 'utf-8');
  console.log(`Generated tracks.js with ${files.length} track(s):`);
  files.forEach((f) => console.log(`  - ${f}`));
} catch (err) {
  if (err.code === 'ENOENT') {
    console.error('Error: assets/ directory not found.');
    console.error('Create the assets/ directory and add MP3 files first.');
    process.exit(1);
  }
  throw err;
}
